# CMake generated Testfile for 
# Source directory: D:/OSCEAN/common_utilities/tests
# Build directory: D:/OSCEAN/common_utilities/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CommonUnitTests]=] "D:/OSCEAN/common_utilities/tests/Debug/common_unit_tests.exe")
  set_tests_properties([=[CommonUnitTests]=] PROPERTIES  LABELS "unit;fast" TIMEOUT "120" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;237;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CommonUnitTests]=] "D:/OSCEAN/common_utilities/tests/Release/common_unit_tests.exe")
  set_tests_properties([=[CommonUnitTests]=] PROPERTIES  LABELS "unit;fast" TIMEOUT "120" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;237;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CommonUnitTests]=] "D:/OSCEAN/common_utilities/tests/MinSizeRel/common_unit_tests.exe")
  set_tests_properties([=[CommonUnitTests]=] PROPERTIES  LABELS "unit;fast" TIMEOUT "120" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;237;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CommonUnitTests]=] "D:/OSCEAN/common_utilities/tests/RelWithDebInfo/common_unit_tests.exe")
  set_tests_properties([=[CommonUnitTests]=] PROPERTIES  LABELS "unit;fast" TIMEOUT "120" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;237;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
else()
  add_test([=[CommonUnitTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[IntegrationVerification]=] "D:/OSCEAN/common_utilities/tests/Debug/integration_verification_test.exe")
  set_tests_properties([=[IntegrationVerification]=] PROPERTIES  LABELS "unit;fast" TIMEOUT "120" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;238;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[IntegrationVerification]=] "D:/OSCEAN/common_utilities/tests/Release/integration_verification_test.exe")
  set_tests_properties([=[IntegrationVerification]=] PROPERTIES  LABELS "unit;fast" TIMEOUT "120" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;238;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[IntegrationVerification]=] "D:/OSCEAN/common_utilities/tests/MinSizeRel/integration_verification_test.exe")
  set_tests_properties([=[IntegrationVerification]=] PROPERTIES  LABELS "unit;fast" TIMEOUT "120" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;238;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[IntegrationVerification]=] "D:/OSCEAN/common_utilities/tests/RelWithDebInfo/integration_verification_test.exe")
  set_tests_properties([=[IntegrationVerification]=] PROPERTIES  LABELS "unit;fast" TIMEOUT "120" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;238;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
else()
  add_test([=[IntegrationVerification]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[AsyncFrameworkTests]=] "D:/OSCEAN/common_utilities/tests/Debug/async_framework_tests.exe")
  set_tests_properties([=[AsyncFrameworkTests]=] PROPERTIES  LABELS "unit;medium" TIMEOUT "180" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;239;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[AsyncFrameworkTests]=] "D:/OSCEAN/common_utilities/tests/Release/async_framework_tests.exe")
  set_tests_properties([=[AsyncFrameworkTests]=] PROPERTIES  LABELS "unit;medium" TIMEOUT "180" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;239;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[AsyncFrameworkTests]=] "D:/OSCEAN/common_utilities/tests/MinSizeRel/async_framework_tests.exe")
  set_tests_properties([=[AsyncFrameworkTests]=] PROPERTIES  LABELS "unit;medium" TIMEOUT "180" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;239;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[AsyncFrameworkTests]=] "D:/OSCEAN/common_utilities/tests/RelWithDebInfo/async_framework_tests.exe")
  set_tests_properties([=[AsyncFrameworkTests]=] PROPERTIES  LABELS "unit;medium" TIMEOUT "180" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;239;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
else()
  add_test([=[AsyncFrameworkTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[SIMDManagerTests]=] "D:/OSCEAN/common_utilities/tests/Debug/simd_manager_tests.exe")
  set_tests_properties([=[SIMDManagerTests]=] PROPERTIES  LABELS "unit;medium" TIMEOUT "180" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;240;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[SIMDManagerTests]=] "D:/OSCEAN/common_utilities/tests/Release/simd_manager_tests.exe")
  set_tests_properties([=[SIMDManagerTests]=] PROPERTIES  LABELS "unit;medium" TIMEOUT "180" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;240;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[SIMDManagerTests]=] "D:/OSCEAN/common_utilities/tests/MinSizeRel/simd_manager_tests.exe")
  set_tests_properties([=[SIMDManagerTests]=] PROPERTIES  LABELS "unit;medium" TIMEOUT "180" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;240;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[SIMDManagerTests]=] "D:/OSCEAN/common_utilities/tests/RelWithDebInfo/simd_manager_tests.exe")
  set_tests_properties([=[SIMDManagerTests]=] PROPERTIES  LABELS "unit;medium" TIMEOUT "180" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;240;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
else()
  add_test([=[SIMDManagerTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[UnifiedMemoryManagerTests]=] "D:/OSCEAN/common_utilities/tests/Debug/unified_memory_manager_tests.exe")
  set_tests_properties([=[UnifiedMemoryManagerTests]=] PROPERTIES  LABELS "unit;medium" TIMEOUT "180" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;241;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[UnifiedMemoryManagerTests]=] "D:/OSCEAN/common_utilities/tests/Release/unified_memory_manager_tests.exe")
  set_tests_properties([=[UnifiedMemoryManagerTests]=] PROPERTIES  LABELS "unit;medium" TIMEOUT "180" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;241;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[UnifiedMemoryManagerTests]=] "D:/OSCEAN/common_utilities/tests/MinSizeRel/unified_memory_manager_tests.exe")
  set_tests_properties([=[UnifiedMemoryManagerTests]=] PROPERTIES  LABELS "unit;medium" TIMEOUT "180" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;241;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[UnifiedMemoryManagerTests]=] "D:/OSCEAN/common_utilities/tests/RelWithDebInfo/unified_memory_manager_tests.exe")
  set_tests_properties([=[UnifiedMemoryManagerTests]=] PROPERTIES  LABELS "unit;medium" TIMEOUT "180" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;241;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
else()
  add_test([=[UnifiedMemoryManagerTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[CacheStrategiesTests]=] "D:/OSCEAN/common_utilities/tests/Debug/cache_strategies_tests.exe")
  set_tests_properties([=[CacheStrategiesTests]=] PROPERTIES  LABELS "unit;medium" TIMEOUT "180" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;242;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[CacheStrategiesTests]=] "D:/OSCEAN/common_utilities/tests/Release/cache_strategies_tests.exe")
  set_tests_properties([=[CacheStrategiesTests]=] PROPERTIES  LABELS "unit;medium" TIMEOUT "180" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;242;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[CacheStrategiesTests]=] "D:/OSCEAN/common_utilities/tests/MinSizeRel/cache_strategies_tests.exe")
  set_tests_properties([=[CacheStrategiesTests]=] PROPERTIES  LABELS "unit;medium" TIMEOUT "180" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;242;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[CacheStrategiesTests]=] "D:/OSCEAN/common_utilities/tests/RelWithDebInfo/cache_strategies_tests.exe")
  set_tests_properties([=[CacheStrategiesTests]=] PROPERTIES  LABELS "unit;medium" TIMEOUT "180" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;242;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
else()
  add_test([=[CacheStrategiesTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[LargeFileProcessorTests]=] "D:/OSCEAN/common_utilities/tests/Debug/large_file_processor_tests.exe")
  set_tests_properties([=[LargeFileProcessorTests]=] PROPERTIES  LABELS "unit;medium" TIMEOUT "180" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;243;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[LargeFileProcessorTests]=] "D:/OSCEAN/common_utilities/tests/Release/large_file_processor_tests.exe")
  set_tests_properties([=[LargeFileProcessorTests]=] PROPERTIES  LABELS "unit;medium" TIMEOUT "180" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;243;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[LargeFileProcessorTests]=] "D:/OSCEAN/common_utilities/tests/MinSizeRel/large_file_processor_tests.exe")
  set_tests_properties([=[LargeFileProcessorTests]=] PROPERTIES  LABELS "unit;medium" TIMEOUT "180" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;243;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[LargeFileProcessorTests]=] "D:/OSCEAN/common_utilities/tests/RelWithDebInfo/large_file_processor_tests.exe")
  set_tests_properties([=[LargeFileProcessorTests]=] PROPERTIES  LABELS "unit;medium" TIMEOUT "180" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;243;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
else()
  add_test([=[LargeFileProcessorTests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[PerformanceBenchmark]=] "D:/OSCEAN/common_utilities/tests/Debug/performance_benchmark_test.exe")
  set_tests_properties([=[PerformanceBenchmark]=] PROPERTIES  LABELS "performance;slow" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;244;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[PerformanceBenchmark]=] "D:/OSCEAN/common_utilities/tests/Release/performance_benchmark_test.exe")
  set_tests_properties([=[PerformanceBenchmark]=] PROPERTIES  LABELS "performance;slow" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;244;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[PerformanceBenchmark]=] "D:/OSCEAN/common_utilities/tests/MinSizeRel/performance_benchmark_test.exe")
  set_tests_properties([=[PerformanceBenchmark]=] PROPERTIES  LABELS "performance;slow" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;244;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[PerformanceBenchmark]=] "D:/OSCEAN/common_utilities/tests/RelWithDebInfo/performance_benchmark_test.exe")
  set_tests_properties([=[PerformanceBenchmark]=] PROPERTIES  LABELS "performance;slow" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;244;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
else()
  add_test([=[PerformanceBenchmark]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[ComplexIntegrationScenarios]=] "D:/OSCEAN/common_utilities/tests/Debug/complex_integration_test.exe")
  set_tests_properties([=[ComplexIntegrationScenarios]=] PROPERTIES  LABELS "performance;slow" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;245;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[ComplexIntegrationScenarios]=] "D:/OSCEAN/common_utilities/tests/Release/complex_integration_test.exe")
  set_tests_properties([=[ComplexIntegrationScenarios]=] PROPERTIES  LABELS "performance;slow" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;245;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[ComplexIntegrationScenarios]=] "D:/OSCEAN/common_utilities/tests/MinSizeRel/complex_integration_test.exe")
  set_tests_properties([=[ComplexIntegrationScenarios]=] PROPERTIES  LABELS "performance;slow" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;245;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[ComplexIntegrationScenarios]=] "D:/OSCEAN/common_utilities/tests/RelWithDebInfo/complex_integration_test.exe")
  set_tests_properties([=[ComplexIntegrationScenarios]=] PROPERTIES  LABELS "performance;slow" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/OSCEAN/common_utilities/tests/CMakeLists.txt;245;add_test;D:/OSCEAN/common_utilities/tests/CMakeLists.txt;0;")
else()
  add_test([=[ComplexIntegrationScenarios]=] NOT_AVAILABLE)
endif()
